use crate::{error, models, routes};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
  paths(
    routes::galaxy::get_all_galaxies,
    routes::galaxy::get_galaxy,
    routes::galaxy::create_galaxy,
    routes::galaxy::update_galaxy,
    routes::galaxy::delete_galaxy,
    routes::star::get_all_stars,
    routes::star::get_star,
    routes::star::create_star,
    routes::star::update_star,
    routes::star::delete_star,
    routes::planet::get_all_planets,
    routes::planet::get_planet,
    routes::planet::create_planet,
    routes::planet::update_planet,
    routes::planet::delete_planet,
  ),
  components(
    schemas(
      models::galaxy::Galaxy,
      models::galaxy::CreateGalaxyData,
      models::galaxy::UpdateGalaxyData,
      models::star::Star,
      models::star::CreateStarData,
      models::star::UpdateStarData,
      models::planet::Planet,
      models::planet::ConnectPlanetToStar,
      models::planet::CreatePlanetData,
      models::planet::UpdatePlanetData,
    ),
    responses(
      error::NotFoundResponse,
      error::AlreadyExistsResponse,
      error::ValidationResponse,
      error::InternalErrorResponse,
      routes::galaxy::GalaxiesList,
      routes::galaxy::SpecificGalaxy,
      routes::galaxy::GalaxyCreated,
      routes::galaxy::GalaxyUpdated,
      routes::galaxy::GalaxyDeleted,
      routes::star::StarsList,
      routes::star::SpecificStar,
      routes::star::StarCreated,
      routes::star::StarUpdated,
      routes::star::StarDeleted,
      routes::planet::PlanetsList,
      routes::planet::SpecificPlanet,
      routes::planet::PlanetCreated,
      routes::planet::PlanetUpdated,
      routes::planet::PlanetDeleted,
    )
  )
)]
pub struct ApiSpec;
