apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stars-cert-src
  namespace: cert-manager
spec:
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  secretName: stars-src-tls
  commonName: "*.localhost"
  subject:
    organizations:
      - GWS
  dnsNames:
    - "*.localhost"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: "default,galaxy-.*"
