import createClient, { ClientOptions } from "openapi-fetch";
import type { paths } from "./openapi"; // generated by openapi-typescript

export * from "./openapi";
export * from "./error";

export type Client = ReturnType<typeof createClient<paths>>;

export class ApiClient {
  public client: Client;

  constructor(clientOptions?: ClientOptions) {
    this.client = createClient<paths>(clientOptions);
  }

  get GET() {
    return this.client.GET;
  }

  get POST() {
    return this.client.POST;
  }

  get PUT() {
    return this.client.PUT;
  }

  get DELETE() {
    return this.client.DELETE;
  }
}
